### ISSUE TITLE
Fix extractNewFeatures

### ISSUE THREAD

**Issue by vakila** [vakila/de-stress#22]
- [x] run outside of grails app (using a regular groovy script) instead of with `BackendTestingController`

- [x] ~~Refactor into more than one method? - e.g. separate methods for~~ => decided not to
    - addAttributesToDataSet()
    - setDurationAttributes(instance)
    - setPitchAttributes(instance)
    - *setIntensityAttributes(instance)*

- `SYLL*_F0_RANGE` is always 0 
    - [x] find out why
    - [x] fix it
    - [x] check that this fixes the `SYLL_REL_RANGE` problem too (always undefined)

- [x] Typo in method made max/min values the same - redo

- [x] Redo attribute names 
    - ~~use `-` instead of `_`~~
    - use `F0` in all names (e.g. `SYLL-REL-F0-MEAN`)

- ~~Energy features failing~~ ==> moved to 

-----
- ~~Debug file-specific problems~~ ==> moved to #25
    - Some samples don't seem to get past `FeatureExtractor()` (all new attributes missing)
        - These are still a mystery:
            - 2SR31_FGWB2_510 - tatort ----- couldn't create FeatureExtractor - 500
            - 2SR31_FGWB2_510 - mörder ----- couldn't create FeatureExtractor - 500

                ```
java.lang.ArrayIndexOutOfBoundsException: 500
	at fr.loria.parole.jsnoori.model.speech.pitch.LinearStylization.ComputeLinearStylization(LinearStylization.java:329)
	at fr.loria.parole.jsnoori.model.speech.pitch.LinearStylization.ComputeLinearStylizationF0(LinearStylization.java:128)
	at fr.loria.parole.jsnoori.model.teacher.feedback.PitchAnalysis.computePitch_semitone_style(PitchAnalysis.java:527)
	at fr.loria.parole.jsnoori.model.teacher.feedback.PitchAnalysis.analyzePitch(PitchAnalysis.java:154)
                ```
        - These were due to the `PitchAnalysis.computeDateAccent()` index problem:
            - [x] 2SH05_FGMB2_531 - flagge ----- couldn't create FeatureExtractor - Index: 23, Size: 23
            - [x] 2SH05_FGMB2_531 - ringen ----- couldn't create FeatureExtractor - Index: 23, Size: 23
            - [x] 2SH02_FGMB1_541 - tragen ----- couldn't create FeatureExtractor - Index: 19, Size: 19
            - [x] 2SR15_GGWA2_018 - tschechen ----- couldn't create FeatureExtractor - Index: 14, Size: 14
            - [x] 2SR15_GGWA2_018 - halten ----- couldn't create FeatureExtractor - Index: 14, Size: 14

        - These were due to a missing (incorrectly named) wav file:
            - [x] 2SR31_FGMA2_513 - tatort ----- couldn't create FeatureExtractor - Cannot invoke method getSegmentation() on null object
            - [x] 2SR31_FGMA2_513 - mörder ----- couldn't create FeatureExtractor - Cannot invoke method getSegmentation() on null object

    - `SYLL*_F0_MEAN` missing for 8 FG samples, `SYLL_REL_MIN` and `_MAX` missing for 8 FG samples, `SYLL_REL_MEAN` missing for 9 FG samples

**Comment by vakila** [comment]
Fixed the issue with `computeDateAccent()` using the wrong index - that solves most of these

**Comment by vakila** [comment]
The ones with speaker 513 were due to an incorrect filename in the viwoll repo - fixed it

**Comment by vakila** [comment]
- [ ] Typo in method made max/min values the same - redo

**Comment by vakila** [comment]
Reopening for Energy feature problems

**Comment by vakila** [comment]
Closing and moving energy stuff to https://github.com/vakila/de-stress/issues/27 - the problem is in Jsnoori, not `extractNewFeatures()`
