### ISSUE TITLE
Investigate problematic files

### ISSUE THREAD

**Issue by vakila** [vakila/de-stress#25]
Moved from #22 

- [ ] 2SR31_FGWB2_510 - tatort ----- couldn't create FeatureExtractor - 500
- [ ] 2SR31_FGWB2_510 - mörder ----- couldn't create FeatureExtractor - 500

    ```
java.lang.ArrayIndexOutOfBoundsException: 500
	at fr.loria.parole.jsnoori.model.speech.pitch.LinearStylization.ComputeLinearStylization(LinearStylization.java:329)
	at fr.loria.parole.jsnoori.model.speech.pitch.LinearStylization.ComputeLinearStylizationF0(LinearStylization.java:128)
	at fr.loria.parole.jsnoori.model.teacher.feedback.PitchAnalysis.computePitch_semitone_style(PitchAnalysis.java:527)
	at fr.loria.parole.jsnoori.model.teacher.feedback.PitchAnalysis.analyzePitch(PitchAnalysis.java:154)
    ```

- [ ] 2SR11_FGBA2_557 - manche
        - SYLL1_F0_MEAN empty
        - SYLL1_F0_MAX = 0
        - SYLL1_F0_MIN = 0
        - SYLL_REL_* are therefore also empty/    
- [ ] 2SR31_FGBA2_551 - tatort
        - SYLL0_F0_MEAN empty
        - SYLL0_F0_MAX = 0
        - SYLL0_F0_MIN = 0
        - SYLL_REL_* are therefore also empty/0
- [ ] 2SR15_GGGB1_027 - halten
        - SYLL1_F0_MEAN empty
        - SYLL1_F0_MAX = 0
        - SYLL1_F0_MIN = 0
        - SYLL_REL_* are therefore also empty/0

- [ ] Some files have no `F0_MIN_INDEX` (min values for both syllables are identical)

**Comment by vakila** [comment]
Moved to https://github.com/vakila/thesis-code/issues/74
